### ISSUE TITLE
Recommend to change README.txt to README.md

### ISSUE THREAD

**Issue by EugeneGohh** [jahangiralommin2/jahangiralommin2.github.io#1]
Suggest a change because using <i>Markdown</i> is more approriate and looks nicer.

**Comment by EugeneGohh** [comment]
Feel free to take a look at it.

> Here's a example of a <i>Markdown</i> https://github.com/EugeneGohh/Personal-Portfolio-Website. The file is README.md.

**Comment by jahangiralommin2** [comment]
done ... thanks
